name: 'Epitech Subject MD Converter'
description: 'Convert a md file to an epitech subject or presentation'
inputs:
  files:
    description: 'path of all the md files to convert'
    required: true
runs:
  using: 'docker'
  image: 'docker://epitechcontent/subject_template'
  run: echo "test"
