name: 'Epitech Subject MD Converter'
description: 'Convert a md file to an epitech subject or presentation'
inputs:
  file:
    description: 'path to the file'
    required: true
runs:
  using: 'docker'
  image: 'docker://epitechcontent/subject_template'
  args:
    - ${{ inputs.file }}
